feat: fetch feed based on embed types
neynarxyz/nodejs-sdk pull request #166
Opened 2024-08-28 22:43 UTC by valerierose

2024-08-30 16:31 UTC, Shreyaschorge requested changes
Need changes in OAS

2024-08-30 16:31 UTC, Shreyaschorge commented on src/neynar-api/neynar-api-client.ts
> +  EmbedType,
Need a change in OAS.
Please rename this to `EmbedTypes` since its a plural entity

2024-08-30 16:31 UTC, Shreyaschorge commented on src/neynar-api/v2/openapi-farcaster/apis/feed-api.ts
> +        feed: async (apiKey: string, feedType: FeedType, filterType?: FilterType, fid?: number, fids?: string, parentUrl?: string, channelId?: string, embedUrl?: string, embedTypes?: Array<EmbedType>
Need a change in OAS:
`embedTypes` is not an array it should be a string. (this gets converted into an array in the middleware, but API accepts it as a string)

2024-08-30 16:31 UTC, Shreyaschorge commented on src/neynar-api/v2/client.ts
> +      embedTypes?: EmbedType[];
Here we can accept it as an array and convert it into a comma separated string before passing it on

2024-08-30 23:33 UTC, manan19 commented
talked with @valerierose about this
- we can keep using an array of enums since explode = false is supported at the OAS level https://swagger.io/docs/specification/serialization/
- defining a type for the [] of embed types is optional

2024-09-04 22:05 UTC, Shreyaschorge commented on src/neynar-api/neynar-api-client.ts
> +      embedType?: EmbedType[];
This should be `embedTypes` cuz fetchFeed in src/neynar-api/v2/client.ts expects `options?.embedTypes`

2024-09-04 22:18 UTC, merged