feat: add lookupUserByUsernameV2()
neynarxyz/nodejs-sdk pull request #192
Opened 2024-10-08 23:06 UTC by eurbs

- **feat: add lookupUserByUsernameV2()**
    - Retrieves the specified user via their username (if found).
    - Docs: https://docs.neynar.com/reference/user-by-username-v2

2024-10-09 14:50 UTC, Shreyaschorge requested changes
Build is failing
<img width="945" alt="image" src="https://github.com/user-attachments/assets/5e731601-b217-4d28-a611-8499d2d386be">

2024-10-10 20:37 UTC, eurbs commented on src/neynar-api/v1/client.ts
> +          'x-api-key': apiKey,
@Shreyaschorge this change seems to have worked. tests:

```js
const apiKey = '{YOUR API KEY HERE}'
const clientV1 = new NeynarV1APIClient(apiKey, { basePath: 'https://api.neynar.com'});

clientV1.fetchRecentUsers({viewerFid: 3, limit: 1}).then(response => console.log('fetchRecentUsers res:', response));
clientV1.fetchAllCastsLikedByUser(3, {viewerFid: 3, limit: 1}).then(response => console.log('fetchAllCastsLikedByUser res:', response));
clientV1.lookupUserByFid(3, 3).then(response => console.log('fetchAllCastsLikedByUser res:', response));
clientV1.lookupUserByUsername('manan', 3).then(response => console.log('lookupUserByUsername res:', response));
clientV1.lookupCustodyAddressForUser(3).then(response => console.log('lookupCustodyAddressForUser res:', response));
```

2024-10-11 12:16 UTC, Shreyaschorge requested changes

2024-10-11 12:16 UTC, Shreyaschorge commented on src/neynar-api/v1/client.ts
> +          'x-api-key': apiKey,
@eurbs You can remove this line, it'll work regardless of this, cuz we are assigning apiKey when we instantiate a config object

```
new Configuration({
      basePath: basePath ? `${basePath}/v1` : BASE_PATH,
      apiKey: apiKey,
    })
```

2024-10-11 16:46 UTC, Shreyaschorge approved these changes
LGTM

2024-10-11 16:46 UTC, merged