draft
neynarxyz/nodejs-sdk pull request #93
Opened 2024-04-15 18:17 UTC by MrKevinOConnell

2024-04-15 19:34 UTC, Shreyaschorge requested changes
@MrKevinOConnell Please update the JSDocs with the updated limit for `fetchAllNotifications`, `fetchChannelNotificationsForUser`, `fetchNotificationsByParentUrlForUser`. The rest looks good.
Also please sync-up with the OAS changes it'll remove allof.

2024-04-15 20:35 UTC, MrKevinOConnell commented
@Shreyaschorge seems like the updated limits are correct

2024-04-16 04:57 UTC, Shreyaschorge commented
> OAS

@MrKevinOConnell I meant it needs to be updated in methods documentation where we give an example of how to use a method.

2024-04-16 05:31 UTC, Shreyaschorge requested changes

2024-04-16 05:31 UTC, Shreyaschorge commented on src/neynar-api/v2/client.ts
> +   * @param {number} [options.limit=25] - Number of results to retrieve (default 15, max 25).
One last change, then its good to merge.
default limit is 15

2024-04-16 05:38 UTC, Shreyaschorge approved these changes

2024-04-16 05:38 UTC, merged